<?php
/**
 * Storage path configuration for the Animation Post-Processing Manager.
 *
 * These are the DEFAULTS for the production server (signcollect.nl). To run on
 * another machine, do NOT edit this file — copy it to `paths.local.php` (which
 * is gitignored), keep only the keys you need to change, and return that array.
 * Values from paths.local.php are merged over these defaults by
 * App\config\Paths.
 *
 * Every directory value must be an absolute path; a trailing slash is optional.
 * "Web-served" means the directory is reachable through Apache under the same
 * relative path, i.e. `web_root` + `/gebarenoverleg_media/...`.
 */
return [

    /*
     * Apache document root. The app lives at <web_root>/animMIDI and is served
     * under the /animMIDI/ URL prefix. Disk paths inside this directory are
     * turned into browser URLs by stripping this prefix (e.g. for the preview
     * viewer's ?anim= parameter), so anything the browser must fetch — GLBs,
     * preview MP4s — has to live (or be symlinked) below it.
     */
    'web_root' => '/web',

    /*
     * Original motion-capture exports from the signCollect pipeline, as FBX and
     * GLB, in the "CC" (Character Creator rig) variant. Read-only for this app.
     * Used for: single/bulk "original" downloads, and as the animation the 3D
     * preview viewer loads (its bone names match the Palmer avatar). If a file
     * is missing here it is fetched from `remote_fbx_base_url` instead.
     * Web-served (GLBs are loaded by the browser).
     */
    'fbx_original' => '/web/gebarenoverleg_media/fbx/CC/',

    /*
     * Post-processed animations uploaded back by the engineers (Unreal export),
     * FBX and GLB. This is the only directory the app WRITES to (uploads); it
     * is created on first upload if absent.
     * Used for: upload destination, "processed" downloads, EAF take bundles,
     * the compare viewer (original vs post-processed).
     * Web-served.
     */
    'fbx_processed' => '/web/gebarenoverleg_media/fbx/post_processed/',

    /*
     * Full-resolution Blackmagic studio recordings, one sub-folder per capture
     * date (YYYY-MM-DD/<take>.mp4). Last-resort video source when neither the
     * mini MP4 nor the Razer MKV exists for a take.
     */
    'blackmagic_full' => '/web/gebarenoverleg_media/studioFiles/blackmagic_files/',

    /*
     * Downscaled (~0.3 MB) preview MP4s of the Blackmagic recordings, same
     * YYYY-MM-DD/<take>.mp4 layout. Preferred video for the preview sidebar and
     * for download bundles because of its size. Coverage starts 2026-05-11;
     * older takes fall back to `razer_mkv`.
     *
     * NOTE: "blackamgic" (m/a transposed) is the REAL directory name on disk —
     * it is a symlink to /mnt/bigstorage/blackmagic_filesMini/. Do not
     * "correct" the spelling or every lookup silently fails.
     * Web-served (the preview sidebar streams it).
     */
    'blackmagic_mini' => '/web/gebarenoverleg_media/blackamgic_filesMini/',

    /*
     * Raw Razer camera recordings (MKV, ~8.6 MB per take), flat directory,
     * file names come from the `vicon_files` table. Fallback video for takes
     * that have no mini MP4. Lives on the big storage volume, NOT under
     * web_root, so it has its own URL prefix below.
     */
    'razer_mkv' => '/mnt/bigstorage/razerFiles/',

    /*
     * Browser URL prefix that serves `razer_mkv` (an Apache alias/symlink).
     * Used by the preview sidebar when falling back to an MKV.
     */
    'razer_mkv_url' => '/gebarenoverleg_media/razerFiles/',

    /*
     * ELAN annotation files (<take>.eaf plus .srt sidecars) produced by the
     * "zin" annotation project. Read-only. Used for: MCP Klaar + EAF filter and
     * the batch EAF/SRT download. A take without an .eaf here is reported as
     * missing in the download's README rather than silently skipped.
     */
    'eaf_dir' => '/web/zin/eaf/zin/',

    /*
     * Public base URL of the original FBX files. Only used as a fallback when a
     * file is not found in `fbx_original` locally: it is downloaded over HTTPS
     * to a temp file, served, and deleted. Set to '' to disable the fallback.
     */
    'remote_fbx_base_url' => 'https://signcollect.nl/gebarenoverleg_media/fbx/',
];
